variable "app_name" { type = string }
variable "environment" { type = string }
variable "aws_region" { type = string }
variable "vpc_id" { type = string }
variable "public_subnet_ids" { type = list(string) }
variable "private_subnet_ids" { type = list(string) }
variable "alb_security_group_id" { type = string }
variable "app_security_group_id" { type = string }
variable "ecr_repository_url" { type = string }
variable "image_tag" { type = string }
variable "app_cpu" { type = number }
variable "app_memory" { type = number }
variable "worker_cpu" { type = number }
variable "worker_memory" { type = number }
variable "app_count" { type = number }
variable "worker_count" { type = number }
variable "ssm_parameter_arn" { type = string }
variable "s3_bucket_name" { type = string }
variable "db_host" { type = string }
variable "db_name" { type = string }
variable "db_username" { type = string }
variable "db_password_arn" { type = string }
variable "redis_host" { type = string }
variable "certificate_arn" { type = string }
variable "alert_email" {
  description = "Email to receive CloudWatch alarm notifications (leave empty to skip)"
  type        = string
  default     = ""
}
